language: python
python:
  - "3.6"
cache: pip
install:
  - pip install coverage
  - pip install coveralls
  - pip install matplotlib
  - pip install numpy
  - pip install scipy
  - pip install .
script:
    # Output something every 5 minutes or Travis kills the tests
    - while sleep 5m; do echo -e "\n=====[ Ran for $SECONDS seconds ]=====\n"; done &
    - coverage run -m unittest discover
    # Killing background sleep loop
    - kill %1
after_success:
  - coveralls
